---
- hosts: appservers 
  become: True
  tasks:
    - name: Install apache
      apt:
        name: "apache2"
        state: "present"
        update_cache: yes
    - name: ensure apache started
      service:
        name: apache2
        state: started
        enabled: yes
    - name: Deploy static website
      copy:
        src: index.html
        dest: /var/www/html/
...
